export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_USERNAME_EXISTS = 'SET_USERNAME_EXISTS';
export const SET_EMAIL_EXISTS = 'SET_EMAIL_EXISTS';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';