// Register
export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_USERNAME_EXISTS = 'SET_USERNAME_EXISTS';
export const SET_EMAIL_EXISTS = 'SET_EMAIL_EXISTS';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';

export const CREATEDECK_EDITDECKNAME = 'CREATEDECK_EDITDECKNAME';

// Flashcards section
export const FLASHCARDS_DECKFLASHCARDS = 'FLASHCARDS_DECKFLASHCARDS';
export const set_DecksHome = 'GETDECKS_DECKNAME';
export const CREATEDECK_EDIT_DECKNAME = 'CREATEDECK_EDIT_DECKNAME';
export const CREATEDECK_SET_ISLOADING = 'CREATEDECK_SET_ISLOADING';
export const SET_PLAYING_CARDS = 'SET_PLAYING_CARDS';
export const SET_CORRECT_CARDS = 'SET_CORRECT_CARDS';
export const SET_WRONG_CARDS = 'SET_WRONG_CARDS';
export const SET_ACTIVE_CARD = 'SET_ACTIVE_CARD';
export const FLASHCARDS_SET_ISSAVING = 'FLASHCARDS_SET_ISSAVING';

// decks
export const DECKS_ADD_DECK = 'DECKS_ADD_DECK';
export const DECKS_SET_USER_DECKS = 'DECKS_SET_USER_DECKS';
export const DECKS_SET_ISLOADING = 'DECKS_SET_ISLOADING';
export const DECKS_SET_DECK = 'DECKS_SET_DECK';
export const FLASHCARDS_SET_ISLOADING = 'FLASHCARDS_SET_ISLOADING';
export const DECKS_SET_DECK_DATA = 'DECKS_SET_DECK_DATA';
export const DECKS_SET_USERDECKS_DECKS = 'DECKS_SET_USERDECKS_DECKS';
export const DECK_EDIT_DATA = 'DECK_EDIT_DATA';
export const CREATEDECK_ADD_TAG = 'CREATEDECK_ADD_TAG';
export const CREATEDECK_DELETE_TAG = 'CREATEDECK_DELETE_TAG';
export const CREATEDECK_CLEAR_TAGS = 'CREATEDECK_CLEAR_TAGS';
export const DECK_DELETE_TAG = 'DECK_DELETE_TAG';
export const DECK_FILTERED_DECKS = 'DECK_FILTERED_DECKS';

// login
export const SET_LOGINACTION = 'SET_LOGINACTION';
export const SET_ANONYMOUS_USER = "SET_ANONYMOUS_USER";

// playing
export const RESET_STATE = 'RESET_STATE';
export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_GAME_ID = 'SET_GAME_ID';

// search-deck
export const SEARCH_SET_SEARCH_VALUE = 'SEARCH_SET_SEARCH_VALUE';
export const SEARCH_SUGGESTIONS = 'SEARCH_SEARCH_SUGGESTIONS';
export const SEARCH_SET_IS_LOADING = 'SEARCH_SET_IS_LOADING';

// filter
export const FILTER_SET_TAGS = 'FILTER_SET_TAGS';
export const DELETE_FILTERED_TAG = 'DELETE_FILTERED_TAG';
export const CLEAR_FILTERED_TAGS = 'CLEAR_FILTERED_TAGS';