export const CREATEDECK_EDITDECKNAME = 'CREATEDECK_EDITDECKNAME';
// Flashcards section
export const FLASHCARDS_DECKFLASHCARDS = 'FLASHCARDS_DECKFLASHCARDS';
export const set_DecksHome = 'GETDECKS_DECKNAME';
export const CREATEDECK_EDIT_DECKNAME = 'CREATEDECK_EDIT_DECKNAME';
export const CREATEDECK_SET_ISLOADING = 'CREATEDECK_SET_ISLOADING';
export const SET_PLAYING_CARDS = 'SET_PLAYING_CARDS';
export const SET_CORRECT_CARDS = 'SET_CORRECT_CARDS';
export const SET_WRONG_CARDS = 'SET_WRONG_CARDS';
export const SET_ACTIVE_CARD = 'SET_ACTIVE_CARD';
export const FLASHCARDS_SET_ISSAVING = 'FLASHCARDS_SET_ISSAVING';

// decks
export const DECKS_ADD_DECK = 'DECKS_ADD_DECK';
export const DECKS_SET_USER_DECKS = 'DECKS_SET_USER_DECKS';
export const DECKS_SET_ISLOADING = 'DECKS_SET_ISLOADING';
export const DECKS_SET_DECK = 'DECKS_SET_DECK';
export const FLASHCARDS_SET_ISLOADING = 'FLASHCARDS_SET_ISLOADING';
export const DECKS_SET_DECK_DATA = 'DECKS_SET_DECK_DATA';
export const DECKS_SET_USERDECKS_DECKS = 'DECKS_SET_USERDECKS_DECKS'
export const DECK_EDIT_DATA = 'DECK_EDIT_DATA';


// login
export const SET_LOGINACTION = 'SET_LOGINACTION';
export const SET_ANONYMOUS_USER = "SET_ANONYMOUS_USER";

// playing
export const RESET_STATE = 'RESET_STATE';
export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_GAME_ID = 'SET_GAME_ID';

// search
export const SEARCH_SET_SEARCH_VALUE = 'SEARCH_SET_SEARCH_VALUE';
export const SEARCH_SET_IS_LOADING = 'SEARCH_SET_IS_LOADING';
