export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const CREATEDECK_EDITDECKNAME = 'CREATEDECK_EDITDECKNAME';
// Flashcards section
export const FLASHCARDS_DECKFLASHCARDS = 'FLASHCARDS_DECKFLASHCARDS';
export const set_DecksHome = 'GETDECKS_DECKNAME';
export const CREATEDECK_EDIT_DECKNAME = 'CREATEDECK_EDIT_DECKNAME';
export const CREATEDECK_SET_ISLOADING = 'CREATEDECK_SET_ISLOADING';
export const SET_PLAYING_CARDS = 'SET_PLAYING_CARDS';
export const SET_CORRECT_CARDS = 'SET_CORRECT_CARDS';
export const SET_WRONG_CARDS = 'SET_WRONG_CARDS';


// decks
export const DECKS_ADD_DECK = 'DECKS_ADD_DECK';
export const DECKS_SET_USER_CHECKS = 'DECKS_SET_USER_CHECKS';
export const DECKS_SET_ISLOADING = 'DECKS_SET_ISLOADING';
